export type CaptionCategory =
  | 'Creator Viral'
  | 'Cinematic & Luxury'
  | 'Cyberpunk & Tech'
  | 'Minimalist & Doc'
  | '3D & Shaders'
  | 'Retro & Arcade';

export interface TrendyCaptionPreset {
  id: string;
  name: string;
  category: CaptionCategory;
  description: string;
  fontFamily: string;
  fontWeight: number;
  textColor: string;
  activeColor: string;
  backgroundColor?: string;
  strokeColor?: string;
  strokeWidth?: number;
  shadow?: string;
  scaleActive: number;
  rotationActiveDeg: number;
  yOffsetActivePx: number;
  animationType: 'pop' | 'glow' | 'bounce' | 'scramble' | 'typewriter' | 'wave' | 'flip' | 'melt';
}

export const TRENDY_CAPTION_PRESETS: TrendyCaptionPreset[] = [
  // --- CREATOR VIRAL (1-10) ---
  {
    id: 'hormozi-yellow-pop',
    name: 'Alex Hormozi Yellow Pop',
    category: 'Creator Viral',
    description: 'High-contrast bold font with black highlight box and yellow keyword pop',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#ffffff',
    activeColor: '#facc15',
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    strokeColor: '#000000',
    strokeWidth: 2,
    shadow: '0 4px 0 #000000',
    scaleActive: 1.22,
    rotationActiveDeg: -2,
    yOffsetActivePx: -6,
    animationType: 'pop',
  },
  {
    id: 'mrbeast-comic-shadow',
    name: 'MrBeast Comic Tilt',
    category: 'Creator Viral',
    description: 'Bold tilted comic text with heavy 4px black outline and yellow/blue alternation',
    fontFamily: 'Impact, system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#38bdf8',
    activeColor: '#f59e0b',
    strokeColor: '#000000',
    strokeWidth: 4,
    shadow: '4px 4px 0 #000000',
    scaleActive: 1.25,
    rotationActiveDeg: 6,
    yOffsetActivePx: -8,
    animationType: 'bounce',
  },
  {
    id: 'tiktok-bouncy-glow',
    name: 'TikTok Bouncy Karaoke',
    category: 'Creator Viral',
    description: 'Word-by-word active neon glow with spring scaling',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#94a3b8',
    activeColor: '#ffffff',
    shadow: '0 0 16px rgba(56, 189, 248, 0.8), 0 0 32px #ec4899',
    scaleActive: 1.3,
    rotationActiveDeg: 0,
    yOffsetActivePx: -4,
    animationType: 'glow',
  },
  {
    id: 'ali-abdaal-minimal',
    name: 'Ali Abdaal Clean Sans',
    category: 'Creator Viral',
    description: 'Clean modern sans-serif with subtle warm yellow marker pill',
    fontFamily: 'Inter, system-ui, sans-serif',
    fontWeight: 700,
    textColor: '#e2e8f0',
    activeColor: '#090e1a',
    backgroundColor: '#fef08a',
    scaleActive: 1.05,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'pop',
  },
  {
    id: 'iman-gadzhi-gold',
    name: 'Iman Gadzhi Luxury Serif',
    category: 'Cinematic & Luxury',
    description: 'Elegant serif typography with golden foil shine and gentle tracking',
    fontFamily: 'Georgia, serif',
    fontWeight: 700,
    textColor: '#cbd5e1',
    activeColor: '#fbbf24',
    shadow: '0 0 12px rgba(251, 191, 36, 0.6)',
    scaleActive: 1.12,
    rotationActiveDeg: 0,
    yOffsetActivePx: -3,
    animationType: 'glow',
  },
  {
    id: 'devon-rodriguez-marker',
    name: 'Handwritten Marker Felt',
    category: 'Creator Viral',
    description: 'Organic felt marker font with slight baseline wobble',
    fontFamily: 'Comic Sans MS, cursive, sans-serif',
    fontWeight: 800,
    textColor: '#ffffff',
    activeColor: '#38bdf8',
    shadow: '2px 2px 0 rgba(0,0,0,0.8)',
    scaleActive: 1.15,
    rotationActiveDeg: -3,
    yOffsetActivePx: -4,
    animationType: 'bounce',
  },
  {
    id: 'ryan-trahan-caps',
    name: 'Trahan Bold All-Caps',
    category: 'Creator Viral',
    description: 'Heavy all-caps white lettering with punchy green keyword accents',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#ffffff',
    activeColor: '#10b981',
    strokeColor: '#040711',
    strokeWidth: 3,
    scaleActive: 1.18,
    rotationActiveDeg: 2,
    yOffsetActivePx: -5,
    animationType: 'pop',
  },
  {
    id: 'graham-stephan-finance',
    name: 'Graham Stephan Finance Cash',
    category: 'Creator Viral',
    description: 'Emerald green dollar sign badge with cash icon attachments',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#f8fafc',
    activeColor: '#22c55e',
    shadow: '0 0 12px rgba(34, 197, 94, 0.7)',
    scaleActive: 1.2,
    rotationActiveDeg: 0,
    yOffsetActivePx: -4,
    animationType: 'glow',
  },
  {
    id: 'podcast-equalizer-pill',
    name: 'Podcast Host Equalizer Badge',
    category: 'Minimalist & Doc',
    description: 'Translucent dark pill with glowing cyan active speaker highlight',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 700,
    textColor: '#94a3b8',
    activeColor: '#38bdf8',
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    scaleActive: 1.1,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'pop',
  },
  {
    id: 'karaoke-color-fill',
    name: 'Karaoke Left-to-Right Wipe',
    category: 'Creator Viral',
    description: 'Smooth continuous gradient color wipe across syllable syllables',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#64748b',
    activeColor: '#ec4899',
    scaleActive: 1.15,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'wave',
  },

  // --- CYBERPUNK & TECH (11-20) ---
  {
    id: 'cyberpunk-matrix-rain',
    name: 'Cyberpunk Matrix Terminal',
    category: 'Cyberpunk & Tech',
    description: 'Glowing green monospace text with active decipher scramble',
    fontFamily: 'monospace',
    fontWeight: 700,
    textColor: '#15803d',
    activeColor: '#22c55e',
    shadow: '0 0 10px rgba(34, 197, 94, 0.9)',
    scaleActive: 1.1,
    rotationActiveDeg: 0,
    yOffsetActivePx: 0,
    animationType: 'scramble',
  },
  {
    id: 'neon-synthwave-pink',
    name: 'Synthwave Neon Arc',
    category: 'Cyberpunk & Tech',
    description: 'Hot pink neon gas tube with electrical arc ignition flicker',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#f43f5e',
    activeColor: '#ffffff',
    shadow: '0 0 16px #f43f5e, 0 0 32px #a855f7',
    scaleActive: 1.25,
    rotationActiveDeg: 0,
    yOffsetActivePx: -6,
    animationType: 'glow',
  },
  {
    id: 'glitch-rgb-split',
    name: 'RGB Chromatic Glitch',
    category: 'Cyberpunk & Tech',
    description: 'Horizontal scanline jitter splitting Red and Blue channel offsets',
    fontFamily: 'monospace',
    fontWeight: 800,
    textColor: '#e2e8f0',
    activeColor: '#38bdf8',
    shadow: '-3px 0 #ef4444, 3px 0 #38bdf8',
    scaleActive: 1.18,
    rotationActiveDeg: 2,
    yOffsetActivePx: 0,
    animationType: 'scramble',
  },
  {
    id: 'hud-targeting-reticle',
    name: 'Sci-Fi HUD Targeting',
    category: 'Cyberpunk & Tech',
    description: 'High-tech military HUD font with cyan bracket markers',
    fontFamily: 'monospace',
    fontWeight: 700,
    textColor: '#0284c7',
    activeColor: '#38bdf8',
    backgroundColor: 'rgba(2, 132, 199, 0.15)',
    scaleActive: 1.12,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'pop',
  },
  {
    id: 'laser-engrave-burn',
    name: 'Laser Engrave Spark Burn',
    category: 'Cyberpunk & Tech',
    description: 'Glowing orange laser burn path with spark spray',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#475569',
    activeColor: '#f97316',
    shadow: '0 0 14px rgba(249, 115, 22, 0.9)',
    scaleActive: 1.15,
    rotationActiveDeg: 0,
    yOffsetActivePx: -3,
    animationType: 'glow',
  },
  {
    id: 'split-flap-airport',
    name: 'Split-Flap Flip Board',
    category: 'Cyberpunk & Tech',
    description: 'Mechanical cascading flip cards from airport departure boards',
    fontFamily: 'monospace',
    fontWeight: 800,
    textColor: '#94a3b8',
    activeColor: '#f8fafc',
    backgroundColor: '#0b0f19',
    shadow: '0 2px 4px rgba(0,0,0,0.8)',
    scaleActive: 1.08,
    rotationActiveDeg: 0,
    yOffsetActivePx: 0,
    animationType: 'flip',
  },
  {
    id: 'anamorphic-lens-streak',
    name: 'Anamorphic Blue Streak Flare',
    category: 'Cyberpunk & Tech',
    description: 'Horizontal blue optical streak flare wash over active words',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#64748b',
    activeColor: '#38bdf8',
    shadow: '0 0 20px #38bdf8, 0 0 40px #0284c7',
    scaleActive: 1.2,
    rotationActiveDeg: 0,
    yOffsetActivePx: -4,
    animationType: 'glow',
  },
  {
    id: 'holographic-wireframe',
    name: '3D Hologram Wireframe',
    category: 'Cyberpunk & Tech',
    description: 'Volumetric cyan hologram with scanline sweep flicker',
    fontFamily: 'monospace',
    fontWeight: 700,
    textColor: '#0891b2',
    activeColor: '#22d3ee',
    shadow: '0 0 12px #22d3ee',
    scaleActive: 1.14,
    rotationActiveDeg: 0,
    yOffsetActivePx: -3,
    animationType: 'pop',
  },
  {
    id: 'electric-arc-surge',
    name: 'High-Voltage Electric Surge',
    category: 'Cyberpunk & Tech',
    description: 'Pulsing lightning blue arc burst on keyword hits',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#e0f2fe',
    activeColor: '#38bdf8',
    shadow: '0 0 16px #38bdf8, 0 0 30px #ffffff',
    scaleActive: 1.28,
    rotationActiveDeg: 3,
    yOffsetActivePx: -6,
    animationType: 'bounce',
  },
  {
    id: 'deep-space-starlight',
    name: 'Cosmic Starlight Sparkle',
    category: 'Cyberpunk & Tech',
    description: 'Deep violet starlight gradient with glittering star sparks',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#818cf8',
    activeColor: '#c084fc',
    shadow: '0 0 14px #c084fc',
    scaleActive: 1.2,
    rotationActiveDeg: 0,
    yOffsetActivePx: -4,
    animationType: 'glow',
  },

  // --- 3D & SHADERS (21-30) ---
  {
    id: 'liquid-molten-chrome',
    name: 'Liquid Molten Chrome',
    category: '3D & Shaders',
    description: 'Metallic mercury specular shine and undulating wave ripples',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#94a3b8',
    activeColor: '#f1f5f9',
    shadow: '0 0 14px rgba(255, 255, 255, 0.9), 0 4px 8px rgba(0,0,0,0.8)',
    scaleActive: 1.22,
    rotationActiveDeg: 0,
    yOffsetActivePx: -5,
    animationType: 'melt',
  },
  {
    id: 'origami-3d-fold',
    name: 'Origami 3D Paper Fold',
    category: '3D & Shaders',
    description: 'Geometric 3D angular paper folding and unfolding rotations',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#94a3b8',
    activeColor: '#38bdf8',
    scaleActive: 1.15,
    rotationActiveDeg: 15,
    yOffsetActivePx: -4,
    animationType: 'flip',
  },
  {
    id: 'glassmorphic-frosted-pill',
    name: 'Glassmorphic Frosted Capsule',
    category: '3D & Shaders',
    description: 'Real-time backdrop blur with specular glass border highlights',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 700,
    textColor: '#f8fafc',
    activeColor: '#38bdf8',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    shadow: '0 8px 32px rgba(0,0,0,0.4)',
    scaleActive: 1.12,
    rotationActiveDeg: 0,
    yOffsetActivePx: -3,
    animationType: 'pop',
  },
  {
    id: 'neumorphic-soft-emboss',
    name: 'Neumorphic Soft Emboss',
    category: '3D & Shaders',
    description: 'Dual-light directional soft shadows simulating extruded plastic',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#64748b',
    activeColor: '#38bdf8',
    backgroundColor: '#090e1a',
    shadow: '4px 4px 8px #03050a, -4px -4px 8px #162038',
    scaleActive: 1.1,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'pop',
  },
  {
    id: 'claymorphic-pastel-volume',
    name: 'Claymorphic 3D Pastel Pill',
    category: '3D & Shaders',
    description: 'Soft inflated 3D pillowy surface with rounded inner depth',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#475569',
    activeColor: '#ec4899',
    backgroundColor: '#fce7f3',
    shadow: '0 6px 16px rgba(236, 72, 153, 0.3)',
    scaleActive: 1.16,
    rotationActiveDeg: -2,
    yOffsetActivePx: -4,
    animationType: 'bounce',
  },
  {
    id: 'burning-ember-fire',
    name: 'Burning Ember Fiery Reveal',
    category: '3D & Shaders',
    description: 'Glowing flame front with floating sparks and ash disintegration',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#78350f',
    activeColor: '#f59e0b',
    shadow: '0 0 18px #f59e0b, 0 0 36px #ef4444',
    scaleActive: 1.24,
    rotationActiveDeg: 0,
    yOffsetActivePx: -5,
    animationType: 'glow',
  },
  {
    id: '3d-perspective-extrusion',
    name: '3D Isometric Extrusion',
    category: '3D & Shaders',
    description: 'Extruded isometric depth side-planes with cast ground shadows',
    fontFamily: 'Impact, system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#0284c7',
    activeColor: '#38bdf8',
    shadow: '2px 2px 0 #0369a1, 4px 4px 0 #075985, 6px 6px 0 #0c4a6e',
    scaleActive: 1.2,
    rotationActiveDeg: -4,
    yOffsetActivePx: -6,
    animationType: 'bounce',
  },
  {
    id: 'fluid-wave-undulation',
    name: 'Kinetic Sine Wave Undulation',
    category: '3D & Shaders',
    description: 'Characters undulate vertically along a continuous traveling wave',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#64748b',
    activeColor: '#06b6d4',
    scaleActive: 1.18,
    rotationActiveDeg: 0,
    yOffsetActivePx: -8,
    animationType: 'wave',
  },
  {
    id: 'sub-glyph-hop',
    name: 'Sub-Glyph Bouncing Dots',
    category: '3D & Shaders',
    description: 'Dots of "i" and accents hop with elastic spring momentum',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#94a3b8',
    activeColor: '#38bdf8',
    scaleActive: 1.15,
    rotationActiveDeg: 4,
    yOffsetActivePx: -5,
    animationType: 'bounce',
  },
  {
    id: 'gold-trophy-foil',
    name: 'Golden Trophy Foil Stamping',
    category: 'Cinematic & Luxury',
    description: 'Reflective gold foil shader with specular glints across letters',
    fontFamily: 'Georgia, serif',
    fontWeight: 800,
    textColor: '#78350f',
    activeColor: '#fbbf24',
    shadow: '0 0 16px rgba(251, 191, 36, 0.8)',
    scaleActive: 1.2,
    rotationActiveDeg: 0,
    yOffsetActivePx: -4,
    animationType: 'glow',
  },

  // --- MINIMALIST & DOC (31-40) ---
  {
    id: 'documentary-lower-third',
    name: 'Documentary Subtitle Rule',
    category: 'Minimalist & Doc',
    description: 'Crisp subtitle line with subtle sliding cyan accent mark',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 600,
    textColor: '#94a3b8',
    activeColor: '#f8fafc',
    scaleActive: 1.08,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'pop',
  },
  {
    id: 'typewriter-cursor-blink',
    name: 'Classic Typewriter with Blink',
    category: 'Minimalist & Doc',
    description: 'Monospace typewriter mechanics with pulsing amber cursor bar',
    fontFamily: 'monospace',
    fontWeight: 700,
    textColor: '#cbd5e1',
    activeColor: '#f59e0b',
    scaleActive: 1.05,
    rotationActiveDeg: 0,
    yOffsetActivePx: 0,
    animationType: 'typewriter',
  },
  {
    id: 'chalkboard-slate-dust',
    name: 'Chalkboard Slate Sketch',
    category: 'Minimalist & Doc',
    description: 'Textured white chalk writing on dark blackboard slate',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 700,
    textColor: '#94a3b8',
    activeColor: '#f1f5f9',
    scaleActive: 1.1,
    rotationActiveDeg: -1,
    yOffsetActivePx: -3,
    animationType: 'pop',
  },
  {
    id: 'swiss-grid-asymmetric',
    name: 'Swiss International Typographic',
    category: 'Minimalist & Doc',
    description: 'Clean Helvetica-inspired layout with solid black underline mark',
    fontFamily: 'Helvetica Neue, Arial, sans-serif',
    fontWeight: 800,
    textColor: '#0f172a',
    activeColor: '#ffffff',
    backgroundColor: '#0f172a',
    scaleActive: 1.06,
    rotationActiveDeg: 0,
    yOffsetActivePx: -1,
    animationType: 'pop',
  },
  {
    id: 'blur-to-focus-snap',
    name: 'Blur-to-Focus Snap In',
    category: 'Minimalist & Doc',
    description: 'Words snap cleanly from 12px Gaussian blur into sharp focus',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#64748b',
    activeColor: '#f8fafc',
    scaleActive: 1.15,
    rotationActiveDeg: 0,
    yOffsetActivePx: -4,
    animationType: 'pop',
  },
  {
    id: 'topographic-elevation-map',
    name: 'Topographic Contour Line',
    category: 'Minimalist & Doc',
    description: 'Geographic elevation contours tracing around subtitle words',
    fontFamily: 'monospace',
    fontWeight: 700,
    textColor: '#0d9488',
    activeColor: '#14b8a6',
    scaleActive: 1.12,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'glow',
  },
  {
    id: 'word-stagger-rise',
    name: 'Word Stagger Cascade Rise',
    category: 'Minimalist & Doc',
    description: 'Each word emerges smoothly from below baseline with spring settle',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#94a3b8',
    activeColor: '#38bdf8',
    scaleActive: 1.14,
    rotationActiveDeg: 0,
    yOffsetActivePx: -6,
    animationType: 'pop',
  },
  {
    id: 'boxed-marker-swatch',
    name: 'Highlighter Pen Swatch',
    category: 'Minimalist & Doc',
    description: 'Simulates fluorescent green highlighter pen drawing over text',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#0f172a',
    activeColor: '#090e1a',
    backgroundColor: '#86efac',
    scaleActive: 1.08,
    rotationActiveDeg: 0,
    yOffsetActivePx: -2,
    animationType: 'pop',
  },
  {
    id: 'staccato-jitter-pop',
    name: 'Staccato Rhythm Jitter',
    category: 'Minimalist & Doc',
    description: 'Sharp rhythmic staccato hits aligned to musical tempo transients',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#cbd5e1',
    activeColor: '#ec4899',
    scaleActive: 1.25,
    rotationActiveDeg: 3,
    yOffsetActivePx: -5,
    animationType: 'bounce',
  },
  {
    id: 'heavy-impact-thud',
    name: 'Heavy Impact Kinetic Thud',
    category: 'Minimalist & Doc',
    description: 'High-mass kinetic drop from top with crisp dead-stop landing',
    fontFamily: 'Impact, system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#64748b',
    activeColor: '#ffffff',
    shadow: '0 6px 12px rgba(0,0,0,0.9)',
    scaleActive: 1.3,
    rotationActiveDeg: 0,
    yOffsetActivePx: -6,
    animationType: 'pop',
  },

  // --- RETRO & ARCADE (41-47) ---
  {
    id: 'retro-8bit-arcade',
    name: 'Retro 8-Bit Pixel Arcade',
    category: 'Retro & Arcade',
    description: 'Chunky pixelated arcade font with glowing green CRT scanlines',
    fontFamily: 'monospace',
    fontWeight: 900,
    textColor: '#15803d',
    activeColor: '#4ade80',
    shadow: '2px 2px 0 #052e16',
    scaleActive: 1.15,
    rotationActiveDeg: 0,
    yOffsetActivePx: -3,
    animationType: 'pop',
  },
  {
    id: 'vaporwave-pastel-sunset',
    name: 'Vaporwave Pastel Sunset',
    category: 'Retro & Arcade',
    description: 'Dreamy pink-to-cyan gradient with retro wireframe grid aesthetics',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#f472b6',
    activeColor: '#38bdf8',
    shadow: '0 0 14px rgba(244, 114, 182, 0.8)',
    scaleActive: 1.2,
    rotationActiveDeg: -2,
    yOffsetActivePx: -4,
    animationType: 'glow',
  },
  {
    id: 'neo-brutalist-black-shadow',
    name: 'Neo-Brutalist Solid Shadow',
    category: 'Retro & Arcade',
    description: 'High-contrast bold font with hard solid unblurred black drop shadow',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#000000',
    activeColor: '#facc15',
    backgroundColor: '#000000',
    shadow: '5px 5px 0 #000000',
    scaleActive: 1.2,
    rotationActiveDeg: 2,
    yOffsetActivePx: -6,
    animationType: 'bounce',
  },
  {
    id: 'comic-book-pow-bubble',
    name: 'Comic Book POW Bubble',
    category: 'Retro & Arcade',
    description: 'Action comic lettering with burst balloon outline and star pop',
    fontFamily: 'Impact, system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#ffffff',
    activeColor: '#ef4444',
    strokeColor: '#000000',
    strokeWidth: 3,
    shadow: '0 0 16px rgba(239, 68, 68, 0.8)',
    scaleActive: 1.35,
    rotationActiveDeg: -6,
    yOffsetActivePx: -8,
    animationType: 'bounce',
  },
  {
    id: 'y2k-glossy-chrome-pill',
    name: 'Y2K Glossy Chrome Bubble',
    category: 'Retro & Arcade',
    description: 'Late 90s bubbly chrome gradients with bright lens glints',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 900,
    textColor: '#94a3b8',
    activeColor: '#38bdf8',
    shadow: '0 4px 12px rgba(56, 189, 248, 0.6)',
    scaleActive: 1.22,
    rotationActiveDeg: 0,
    yOffsetActivePx: -5,
    animationType: 'melt',
  },
  {
    id: 'rotational-card-swivel',
    name: 'Rotational 3D Card Swivel',
    category: 'Retro & Arcade',
    description: 'Words swivel around the Y-axis as if turning playing cards',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 800,
    textColor: '#cbd5e1',
    activeColor: '#f59e0b',
    scaleActive: 1.18,
    rotationActiveDeg: 180,
    yOffsetActivePx: -4,
    animationType: 'flip',
  },
  {
    id: 'floating-zero-g-drift',
    name: 'Floating Zero-G Drift',
    category: 'Retro & Arcade',
    description: 'Gentle weightless floating motion with continuous sine wave bob',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 700,
    textColor: '#94a3b8',
    activeColor: '#a855f7',
    shadow: '0 0 14px rgba(168, 85, 247, 0.7)',
    scaleActive: 1.15,
    rotationActiveDeg: 3,
    yOffsetActivePx: -6,
    animationType: 'wave',
  },
];
